<?xml version="1.0" encoding="utf-8"?><Database Name="SmartShopping_DB" Class="SmartDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=KOBKULPHOTI2166\SQLEXPRESS;Initial Catalog=SmartShopping_DB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SmartShopping_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Inventory" Member="Inventories">
    <Type Name="Inventory">
      <Column Name="inventory_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="unit" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="pro_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="exp_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="store_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Member" Member="Members">
    <Type Name="Member">
      <Column Name="member_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="member_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="mobile" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Store" Member="Stores">
    <Type Name="Store">
      <Column Name="store_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="store_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="location" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staff_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mamber_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="store_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="product_des" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="price" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ProductPicking" Member="ProductPickings">
    <Type Name="ProductPicking">
      <Column Name="productPicker_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="product_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Receipt" Member="Receipts">
    <Type Name="Receipt">
      <Column Name="receipt_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="date" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="order_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="staff_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="staff_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="store_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mobile" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>